MAX_NUM: 2000
BATCH_SIZE: 32
MODE_NAME: "BLIP"
TASK: "itc"
DATA:
  TYPES: ["Attribute/action","Attribute/color","Attribute/material","Attribute/size","Attribute/state"]
  TEST_DATA: ["vg","vaw"]
OUTPUT:
  DIR: "vl-checklist"
  NUM: 4
